---
# These task install application

#- name: update packages
  #yum: update_cache=yes
- name: install updates
  yum: update_cache=yes
 # when: ansible_os_family == "RedHat
- name: install git, curl, make, nodejs etc.
  yum: pkg={{item}} state=present
  with_items:
    - gcc
    - g++
    - curl
    - make
    - libv8-dev
    - nodejs
    - libssl-dev
    - libxml2-dev
    - zlib1g-dev
    - zsh
    - libreadline-dev
    - libyaml-dev
    - build-essential


